AWSTemplateFormatVersion: '2010-09-09'
Description: 'My Static Website Hosting with S3'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: comcast-coding-challenge
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  MyS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyS3Bucket, '/*']]

Outputs:
  MyWebsiteURL:
    Value: !GetAtt MyS3Bucket.WebsiteURL
    Description: URL for my static website hosted on S3