AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution with HTTP to HTTPS Redirection for S3 Bucket

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: CloudFront Distribution for comcast-coding-challenge
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: comcast-coding-challenge.s3-website.us-east-2.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100
Outputs:
  DistributionId:
    Description: "The CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Description: "The domain name of the CloudFront Distribution"
    Value: !GetAtt CloudFrontDistribution.DomainName
